export const wechatActivity = '/smoke_api/phone/wechatActivity/queryList' //活动列表接口
export const wechatActivityGet = '/smoke_api/phone/wechatActivity/get' //查询活动信息接口
export const wechatActivityAdd = '/smoke_api/phone/wechatActivity/add' //活动新增保存接口
export const wechatActivityEdit =  '/smoke_api/phone/wechatActivity/edit' //活动编辑增保存接口
export const wechatActivityDelete =  '/smoke_api/phone/wechatActivity/delete'//活动删除接口
export const wechatActivityAwardLlist = '/smoke_api/phone/wechatActivity/award/list'//奖品列表接口
export const wechatActivityAwardExplain =  '/smoke_api/phone/wechatActivity/award/explain'//奖品说明接口
export const wechatActivityAwardGet = '/smoke_api/phone/wechatActivity/award/get'//奖品新增接口
export const wechatActivityAwardSEdit = '/smoke_api/phone/wechatActivity/award/edit'//奖品新增接口
export const wechatActivityAwardAdd = '/smoke_api/phone/wechatActivity/award/add'//奖品新增接口
export const wechatActivityAwardUserList ='/smoke_api/phone/wechatActivity/award/userList'//中奖列表查询接口
export const wechatActivityAwardSelectAward = '/smoke_api/phone/wechatActivity/award/selectAward'//中奖列表奖品数据接口
export const wechatActivityAwardUserDetail = '/smoke_api/phone/wechatActivity/award/userDetail'//中奖列表详情接口
export const wechatActivityAwardUpdateUser = '/smoke_api/phone/wechatActivity/award/updateUser'//中奖列表用户修改接口
export const wechatActivityAwardPost =  '/smoke_api/phone/wechatActivity/award/post'//中奖列表用户派送接口
export const wechatActivityUserList = '/smoke_api/phone/wechatActivity/userList'//参与用户列表接口
export const getCouponList = '/order-service/coupon/getCouponList' //通过分校获取优惠券